apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-python-azcq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-python-azcq
    app.kubernetes.io/part-of: sample-python
  name: sample-python-azcq
  namespace: bbrownin-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: sample-python-azcq
status:
  loadBalancer: {}
